import { StyleSheet } from "react-native";

const addItemStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff5ee",
    padding: 20,
    justifyContent: "center",
  },
  heading: {
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 30,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    fontSize: 16,
    marginBottom: 20,
  },
  photoBox: {
    backgroundColor: "#f2effc",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
    marginBottom: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  photoPrompt: {
    marginTop: 12,
    fontSize: 16,
    color: "black",
    textAlign: "center",
  },
  photoButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 10,
  },
  takePhotoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7f61c5",
    borderRadius: 12,
    paddingVertical: 12,
    flex: 1,

    borderBottomWidth: 4,
    borderColor: "#5b4ca3",
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  uploadPhotoButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fdda57",
    borderRadius: 12,
    paddingVertical: 12,
    flex: 1,
    borderBottomWidth: 4,
    borderColor: "#2c3e50",
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  saveButton: {
    backgroundColor: "#60d394",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,

    borderBottomWidth: 6,
    borderColor: "#3da56a",
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopWidth: 2,

    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  photoBtnText: {
    fontWeight: "600",
    marginLeft: 8,
    fontSize: 15,
    color: "#fff",
  },
  saveButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
});

export default addItemStyles;
